### ISSUE TITLE
You cannot register objects without the watcher object! 

### ISSUE THREAD

**Issue by RoboMWM** [dmulloy2/PacketWrapper#24]
Same info as https://github.com/dmulloy2/ProtocolLib/issues/168, albeit running ProtocolLib build 273.

```
Caused by: java.lang.IllegalArgumentException: You cannot register objects witho
ut the watcher object!
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_
1.9.2.jar:git-Paper-691]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedD
ataWatcher.java:362) ~[?:?]
        at tk.maciekmm.antiaura.AuraCheck.getSpawnWrapper(AuraCheck.java:125) ~[
?:?]
        at tk.maciekmm.antiaura.AuraCheck.invoke(AuraCheck.java:67) ~[?:?]
        at tk.maciekmm.antiaura.AntiAura.onCommand(AntiAura.java:154) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pat
ched_1.9.2.jar:git-Paper-691]
        ... 12 more
```

Line 125 for reference: https://github.com/RoboMWM/AntiAura/blob/master/src/main/java/tk/maciekmm/antiaura/AuraCheck.java#L125

I guess the WrappedDataWatcher object behaves a little differently now?

**Comment by dmulloy2** [comment]
Registering new objects requires the watcher object. Watcher objects contain the index and serializer. See here for more: http://ci.dmulloy2.net/job/ProtocolLib/javadoc/com/comphenix/protocol/wrappers/WrappedDataWatcher.WrappedDataWatcherObject.html
